spring.application.name=springBootfirstapp

jwt.secret.access=YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWE=
jwt.secret.refresh=YmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmI=

spring.datasource.url=jdbc:postgresql://localhost:5432/recipes_db
spring.datasource.username=postgres
spring.datasource.password=Zhanel1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true